### ISSUE TITLE
File change doesn't work anymore from Nova v4.22.0

### ISSUE THREAD

**Issue by eullercdr** [ctessier/nova-advanced-image-field#96] opened 2023-02-13 19:00 UTC
@ctessier Can you tell me why the package is not working anymore? I'm using the latest version of Nova.

**Comment by eullercdr** [comment] 2023-02-13 19:51
I am using "ctessier/nova-advanced-image-field": "^2.0".

**Comment by eullercdr** [comment] 2023-02-13 19:52
@ctessier I am using the version `ctessier/nova-advanced-image-field": "^2.0`

**Comment by ctessier** [comment] 2023-02-14 10:25
OK
You should be a little more specific though...

What doesn't work anymore? Which version of Nova? What error do you get? What does you resource class look like? What is your version of PHP?

**Comment by mziraki** [comment] 2023-02-14 10:56
@ctessier it's v4.22.0, it's working on v4.21.0

**Comment by ctessier** [comment] 2023-02-14 20:11
I can't reproduce any issue with Nova v4.22.0

Guys! Give me a little more to work from here! 
What doesn't work anymore? What error do you get? What does you resource class look like? What is your version of PHP?

**Comment by puzzledmonkey** [comment] 2023-02-15 05:34
it doesn't work with Nova 4.22.0 because they changed the behaviour of DropZone
![image](https://user-images.githubusercontent.com/3913622/218941454-1a3a9033-4036-4923-a42f-0ea4c34b7fc2.png)
in short, you need to update to use @file-changed="handleFileChange" instead of just @change="handleFileChange"
presumably you can use both of them to ensure backwards compatibility too?

**Comment by puzzledmonkey** [comment] 2023-02-15 05:37
https://github.com/ctessier/nova-advanced-image-field/pull/97

I've tested and with the @change line kept as well as the new @file-changed line, it works in Nova <4.22.0 too.

:)

**Comment by ctessier** [comment] 2023-02-15 07:04
Thank you @puzzledmonkey 

I'll have a look at your PR asap!
I didn't have any issue while choosing a file, is only the dropzone affected?

**Comment by puzzledmonkey** [comment] 2023-02-15 08:51
it doesn't work for me when choosing a file or when dropping a file on the dropzone.

you might have another plugin installed that's overwriting the dropzone code i guess? but here i had no luck with any uploading until i added that @file-changed line.

**Comment by ctessier** [comment] 2023-02-15 22:57
Thank you very much @puzzledmonkey ! 
I was able to reproduce. I will publish a new version with your fix!

Good work, thank you!

**Comment by ctessier** [comment] 2023-02-15 23:41
This issue was fixed in [v2.0.2](https://github.com/ctessier/nova-advanced-image-field/releases/tag/v2.0.2). Thank you @puzzledmonkey for your contribution 😉

**Closed by ctessier** 2023-02-15 23:41 UTC
Labels: bug

**Comment by Woeler** [comment] 2023-02-16 10:00
Cheers for fixing this. Ran into it myself.
